version: '3.8'


services:

    db:
        container_name: project_1_db
        image: postgres:16.1
        restart: always
        volumes:
            - postgres:/var/lib/postgresql/data/
        env_file:
            - .env
        ports:
            - 5432:5432
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
            interval: 10s
            timeout: 5s
            retries: 5

    app:
        container_name: project_1_app
        build: .
        restart: always
        volumes:
            - .:/app/
        env_file:
            - .env
        entrypoint: >
            sh -c "
                alembic upgrade head &&
                uvicorn app.main:app --host 0.0.0.0 --reload
            "
        ports:
            - 8000:8000
        depends_on:
            db:
                condition: service_healthy


volumes:
    postgres:
